### ISSUE TITLE
API Reference Docs

### ISSUE THREAD

**Issue by mpetason** [ibm-cloud-docs/assistant-icp#61]
It may be helpful to link back to how to get the API key in the reference. Unless someone just finished setting this up they may not have saved the API key or remember how to find it. 

API Ref Page - 
https://cloud.ibm.com/apidocs/assistant-icp

2.1.0 Key - 
https://console.bluemix.net/docs/services/assistant-icp/services-information.html#authenticate-api-calls

3.1.0 Key -
https://console.bluemix.net/docs/services/assistant-icp/install_101_on_310.html#install-101-on-310-authenticate-api-calls

**Comment by SirSpidey** [comment]
Thanks for the suggestion. We're not making updates to Watson Assistant for IBM Cloud Private. You can find the active offerings at https://cloud.ibm.com/apidocs?category=ai.
